id: P33426A2E
initial_creation_type: ocr
source_metadata:
  volumes:
    34aff5b581dd499791184b331fdce005:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: ''
      total_pages: 1872
      volume_number: 114
